--------------------------------------------------------
--  File created - Monday-March-23-2020   
--------------------------------------------------------
@C:\Users\공미선\git\SQL\TRADE_DATA_TABLE.sql
@C:\Users\공미선\git\SQL\BOARD_WRITE_DATA_TABLE.sql
@C:\Users\공미선\git\SQL\FAQ_DATA_TABLE.sql
@C:\Users\공미선\git\SQL\CM_COMMENT_DATA_TABLE.sql
@C:\Users\공미선\git\SQL\NOTE_DATA_TABLE.sql
@C:\Users\공미선\git\SQL\REPORT_DATA_TABLE.sql
@C:\Users\공미선\git\SQL\GAME_SORT_DATA_TABLE.sql
@C:\Users\공미선\git\SQL\MEMBER_DATA_TABLE.sql
@C:\Users\공미선\git\SQL\RANK_DATA_TABLE.sql
@C:\Users\공미선\git\SQL\WITHDRAWAL_DATA_TABLE.sql
@C:\Users\공미선\git\SQL\STATISTICS_DATA_TABLE.sql
@C:\Users\공미선\git\SQL\WD_RECORD_DATA_TABLE.sql
@C:\Users\공미선\git\SQL\SCRAP_DATA_TABLE.sql
@C:\Users\공미선\git\SQL\CAFE_DATA_TABLE.sql
@C:\Users\공미선\git\SQL\GAME_PERSON_DATA_TABLE.sql
@C:\Users\공미선\git\SQL\CAFE_REVIEW_DATA_TABLE.sql
@C:\Users\공미선\git\SQL\BOARD_TYPE_DATA_TABLE.sql
@C:\Users\공미선\git\SQL\PAYMENT_DATA_TABLE.sql
@C:\Users\공미선\git\SQL\GAME_DATA_TABLE.sql
@C:\Users\공미선\git\SQL\F_FILE_DATA_TABLE.sql
@C:\Users\공미선\git\SQL\SUBJECT_DATA_TABLE.sql
@C:\Users\공미선\git\SQL\GAME_METHOD_DATA_TABLE.sql
@C:\Users\공미선\git\SQL\SPONSOR_DATA_TABLE.sql
@C:\Users\공미선\git\SQL\BOARD_FILE_DATA_TABLE.sql
@C:\Users\공미선\git\SQL\GAME_CLASS_DATA_TABLE.sql
@C:\Users\공미선\git\SQL\GAME_THEME_DATA_TABLE.sql
