REM INSERTING into CASSIE.MEMBER
SET DEFINE OFF;
Insert into CASSIE.MEMBER (M_NO,M_ID,M_PW,M_NAME,M_BIRTH,M_NICK,M_GENDER,M_POINT,M_PHONE,M_EMAIL,M_POST,M_ADDR1,M_ADDR2,R_NO,M_RE_SMS,M_RE_NOTICE,M_RE_MESSAGE,M_INFO,M_SELF,M_INDATE,M_OUTDATE,M_OUT,M_REPORT_NUM,M_EXTRA,F_NO) values (2,'tester2','2222','member2',to_date('02-JAN-90','DD-MON-RR'),'member_nick2','f',30000,'01011111112','tester2@gmail.com',0,'test','test2',2,'n','n','n','n','자기소개',to_date('19-MAR-20','DD-MON-RR'),null,'n',0,null,1);
Insert into CASSIE.MEMBER (M_NO,M_ID,M_PW,M_NAME,M_BIRTH,M_NICK,M_GENDER,M_POINT,M_PHONE,M_EMAIL,M_POST,M_ADDR1,M_ADDR2,R_NO,M_RE_SMS,M_RE_NOTICE,M_RE_MESSAGE,M_INFO,M_SELF,M_INDATE,M_OUTDATE,M_OUT,M_REPORT_NUM,M_EXTRA,F_NO) values (3,'tester3','3333','member3',to_date('02-JAN-90','DD-MON-RR'),'member_nick3','f',10000,'01011111113','tester3@gmail.com',0,'test','test3',2,'n','n','n','n','자기소개',to_date('19-MAR-20','DD-MON-RR'),null,'n',0,null,1);
Insert into CASSIE.MEMBER (M_NO,M_ID,M_PW,M_NAME,M_BIRTH,M_NICK,M_GENDER,M_POINT,M_PHONE,M_EMAIL,M_POST,M_ADDR1,M_ADDR2,R_NO,M_RE_SMS,M_RE_NOTICE,M_RE_MESSAGE,M_INFO,M_SELF,M_INDATE,M_OUTDATE,M_OUT,M_REPORT_NUM,M_EXTRA,F_NO) values (1,'tester1','1111','member1',to_date('01-JAN-90','DD-MON-RR'),'member_nick1','f',0,'01011111110','tester1@gmail.com',0,'test','test2',3,'n','n','n','n','selftest',to_date('19-MAR-20','DD-MON-RR'),null,'n',0,null,1);
Insert into CASSIE.MEMBER (M_NO,M_ID,M_PW,M_NAME,M_BIRTH,M_NICK,M_GENDER,M_POINT,M_PHONE,M_EMAIL,M_POST,M_ADDR1,M_ADDR2,R_NO,M_RE_SMS,M_RE_NOTICE,M_RE_MESSAGE,M_INFO,M_SELF,M_INDATE,M_OUTDATE,M_OUT,M_REPORT_NUM,M_EXTRA,F_NO) values (4,'tester4','4444','member4',to_date('02-JAN-90','DD-MON-RR'),'member_nick4','f',50000,'01011111114','tester4@gmail.com',0,'test','test4',1,'n','n','n','n','자기소개',to_date('19-MAR-20','DD-MON-RR'),null,'n',0,null,1);
Insert into CASSIE.MEMBER (M_NO,M_ID,M_PW,M_NAME,M_BIRTH,M_NICK,M_GENDER,M_POINT,M_PHONE,M_EMAIL,M_POST,M_ADDR1,M_ADDR2,R_NO,M_RE_SMS,M_RE_NOTICE,M_RE_MESSAGE,M_INFO,M_SELF,M_INDATE,M_OUTDATE,M_OUT,M_REPORT_NUM,M_EXTRA,F_NO) values (5,'tester5','5555','member5',to_date('02-JAN-90','DD-MON-RR'),'member_nick5','f',0,'01011111115','tester5@gmail.com',0,'test','test5',3,'n','n','n','n','자기소개',to_date('19-MAR-20','DD-MON-RR'),null,'n',0,null,1);
Insert into CASSIE.MEMBER (M_NO,M_ID,M_PW,M_NAME,M_BIRTH,M_NICK,M_GENDER,M_POINT,M_PHONE,M_EMAIL,M_POST,M_ADDR1,M_ADDR2,R_NO,M_RE_SMS,M_RE_NOTICE,M_RE_MESSAGE,M_INFO,M_SELF,M_INDATE,M_OUTDATE,M_OUT,M_REPORT_NUM,M_EXTRA,F_NO) values (6,'tester6','6666','member6',to_date('02-JAN-90','DD-MON-RR'),'member_nick6','m',0,'01011111116','tester6@gmail.com',0,'test','test6',3,'n','n','n','n','자기소개',to_date('19-MAR-20','DD-MON-RR'),null,'n',0,null,1);
Insert into CASSIE.MEMBER (M_NO,M_ID,M_PW,M_NAME,M_BIRTH,M_NICK,M_GENDER,M_POINT,M_PHONE,M_EMAIL,M_POST,M_ADDR1,M_ADDR2,R_NO,M_RE_SMS,M_RE_NOTICE,M_RE_MESSAGE,M_INFO,M_SELF,M_INDATE,M_OUTDATE,M_OUT,M_REPORT_NUM,M_EXTRA,F_NO) values (7,'tester7','7777','member7',to_date('02-JAN-90','DD-MON-RR'),'member_nick7','m',0,'01011111117','tester7@gmail.com',0,'test','test7',3,'n','n','n','n','자기소개',to_date('19-MAR-20','DD-MON-RR'),null,'n',0,null,1);
Insert into CASSIE.MEMBER (M_NO,M_ID,M_PW,M_NAME,M_BIRTH,M_NICK,M_GENDER,M_POINT,M_PHONE,M_EMAIL,M_POST,M_ADDR1,M_ADDR2,R_NO,M_RE_SMS,M_RE_NOTICE,M_RE_MESSAGE,M_INFO,M_SELF,M_INDATE,M_OUTDATE,M_OUT,M_REPORT_NUM,M_EXTRA,F_NO) values (8,'tester8','8888','member8',to_date('02-JAN-90','DD-MON-RR'),'member_nick8','m',0,'01011111118','tester8@gmail.com',0,'test','test8',3,'n','n','n','n','자기소개',to_date('19-MAR-20','DD-MON-RR'),null,'n',0,null,1);
Insert into CASSIE.MEMBER (M_NO,M_ID,M_PW,M_NAME,M_BIRTH,M_NICK,M_GENDER,M_POINT,M_PHONE,M_EMAIL,M_POST,M_ADDR1,M_ADDR2,R_NO,M_RE_SMS,M_RE_NOTICE,M_RE_MESSAGE,M_INFO,M_SELF,M_INDATE,M_OUTDATE,M_OUT,M_REPORT_NUM,M_EXTRA,F_NO) values (9,'tester9','9999','member9',to_date('02-JAN-90','DD-MON-RR'),'member_nick9','m',0,'01011111119','tester9@gmail.com',0,'test','test9',3,'n','n','n','n','자기소개',to_date('19-MAR-20','DD-MON-RR'),null,'n',0,null,1);
Insert into CASSIE.MEMBER (M_NO,M_ID,M_PW,M_NAME,M_BIRTH,M_NICK,M_GENDER,M_POINT,M_PHONE,M_EMAIL,M_POST,M_ADDR1,M_ADDR2,R_NO,M_RE_SMS,M_RE_NOTICE,M_RE_MESSAGE,M_INFO,M_SELF,M_INDATE,M_OUTDATE,M_OUT,M_REPORT_NUM,M_EXTRA,F_NO) values (10,'tester10','11111','member10',to_date('02-JAN-90','DD-MON-RR'),'member_nick10','f',0,'01011111120','tester10@gmail.com',0,'test','test10',3,'n','n','n','n','자기소개',to_date('19-MAR-20','DD-MON-RR'),null,'n',0,null,1);
Insert into CASSIE.MEMBER (M_NO,M_ID,M_PW,M_NAME,M_BIRTH,M_NICK,M_GENDER,M_POINT,M_PHONE,M_EMAIL,M_POST,M_ADDR1,M_ADDR2,R_NO,M_RE_SMS,M_RE_NOTICE,M_RE_MESSAGE,M_INFO,M_SELF,M_INDATE,M_OUTDATE,M_OUT,M_REPORT_NUM,M_EXTRA,F_NO) values (11,'tester11','22222','member11',to_date('02-JAN-90','DD-MON-RR'),'member_nick11','f',0,'01011111121','tester11@gmail.com',0,'test','test11',3,'n','n','n','n','자기소개',to_date('19-MAR-20','DD-MON-RR'),null,'n',0,null,1);
Insert into CASSIE.MEMBER (M_NO,M_ID,M_PW,M_NAME,M_BIRTH,M_NICK,M_GENDER,M_POINT,M_PHONE,M_EMAIL,M_POST,M_ADDR1,M_ADDR2,R_NO,M_RE_SMS,M_RE_NOTICE,M_RE_MESSAGE,M_INFO,M_SELF,M_INDATE,M_OUTDATE,M_OUT,M_REPORT_NUM,M_EXTRA,F_NO) values (12,'tester12','33333','member12',to_date('02-JAN-90','DD-MON-RR'),'member_nick12','f',0,'01011111122','tester12@gmail.com',0,'test','test12',3,'n','n','n','n','자기소개',to_date('19-MAR-20','DD-MON-RR'),null,'n',0,null,1);
Insert into CASSIE.MEMBER (M_NO,M_ID,M_PW,M_NAME,M_BIRTH,M_NICK,M_GENDER,M_POINT,M_PHONE,M_EMAIL,M_POST,M_ADDR1,M_ADDR2,R_NO,M_RE_SMS,M_RE_NOTICE,M_RE_MESSAGE,M_INFO,M_SELF,M_INDATE,M_OUTDATE,M_OUT,M_REPORT_NUM,M_EXTRA,F_NO) values (13,'tester13','44444','member13',to_date('02-JAN-90','DD-MON-RR'),'member_nick13','f',0,'01011111123','tester13@gmail.com',0,'test','test13',3,'n','n','n','n','자기소개',to_date('19-MAR-20','DD-MON-RR'),null,'n',0,null,1);
Insert into CASSIE.MEMBER (M_NO,M_ID,M_PW,M_NAME,M_BIRTH,M_NICK,M_GENDER,M_POINT,M_PHONE,M_EMAIL,M_POST,M_ADDR1,M_ADDR2,R_NO,M_RE_SMS,M_RE_NOTICE,M_RE_MESSAGE,M_INFO,M_SELF,M_INDATE,M_OUTDATE,M_OUT,M_REPORT_NUM,M_EXTRA,F_NO) values (14,'tester14','55555','member14',to_date('02-JAN-90','DD-MON-RR'),'member_nick14','f',0,'01011111124','tester14@gmail.com',0,'test','test14',3,'n','n','n','n','자기소개',to_date('19-MAR-20','DD-MON-RR'),null,'n',0,null,1);
Insert into CASSIE.MEMBER (M_NO,M_ID,M_PW,M_NAME,M_BIRTH,M_NICK,M_GENDER,M_POINT,M_PHONE,M_EMAIL,M_POST,M_ADDR1,M_ADDR2,R_NO,M_RE_SMS,M_RE_NOTICE,M_RE_MESSAGE,M_INFO,M_SELF,M_INDATE,M_OUTDATE,M_OUT,M_REPORT_NUM,M_EXTRA,F_NO) values (0,'admin','4321','admin',to_date('02-FEB-90','DD-MON-RR'),'admin_nick','f',0,'01012341234','admin@gmail.com',0,'add',null,0,'n','n','n','n',null,to_date('19-MAR-20','DD-MON-RR'),to_date('19-MAR-20','DD-MON-RR'),'n',0,null,null);
