REM INSERTING into CASSIE.SUBJECT
SET DEFINE OFF;
Insert into CASSIE.SUBJECT (S_NO,BT_NO,S_CONTENT) values (1,1,'잡담');
Insert into CASSIE.SUBJECT (S_NO,BT_NO,S_CONTENT) values (2,1,'노하우');
Insert into CASSIE.SUBJECT (S_NO,BT_NO,S_CONTENT) values (3,1,'토론');
Insert into CASSIE.SUBJECT (S_NO,BT_NO,S_CONTENT) values (4,2,'개봉기');
Insert into CASSIE.SUBJECT (S_NO,BT_NO,S_CONTENT) values (5,2,'일 리뷰');
Insert into CASSIE.SUBJECT (S_NO,BT_NO,S_CONTENT) values (6,2,'다 리뷰');
Insert into CASSIE.SUBJECT (S_NO,BT_NO,S_CONTENT) values (7,3,'모집');
Insert into CASSIE.SUBJECT (S_NO,BT_NO,S_CONTENT) values (8,3,'모임 후기');
Insert into CASSIE.SUBJECT (S_NO,BT_NO,S_CONTENT) values (9,4,'이벤트');
Insert into CASSIE.SUBJECT (S_NO,BT_NO,S_CONTENT) values (10,4,'대회');
Insert into CASSIE.SUBJECT (S_NO,BT_NO,S_CONTENT) values (11,4,'신작 소식');
Insert into CASSIE.SUBJECT (S_NO,BT_NO,S_CONTENT) values (12,4,'세일');
Insert into CASSIE.SUBJECT (S_NO,BT_NO,S_CONTENT) values (13,4,'기타');
Insert into CASSIE.SUBJECT (S_NO,BT_NO,S_CONTENT) values (14,5,'룰');
Insert into CASSIE.SUBJECT (S_NO,BT_NO,S_CONTENT) values (15,5,'추천');
Insert into CASSIE.SUBJECT (S_NO,BT_NO,S_CONTENT) values (16,5,'기타');
Insert into CASSIE.SUBJECT (S_NO,BT_NO,S_CONTENT) values (17,6,'계획');
Insert into CASSIE.SUBJECT (S_NO,BT_NO,S_CONTENT) values (18,6,'디자인');
Insert into CASSIE.SUBJECT (S_NO,BT_NO,S_CONTENT) values (19,6,'완성');
Insert into CASSIE.SUBJECT (S_NO,BT_NO,S_CONTENT) values (20,6,'공유');
Insert into CASSIE.SUBJECT (S_NO,BT_NO,S_CONTENT) values (21,6,'테스트플레이');
Insert into CASSIE.SUBJECT (S_NO,BT_NO,S_CONTENT) values (22,7,'회원');
Insert into CASSIE.SUBJECT (S_NO,BT_NO,S_CONTENT) values (23,7,'결제');
Insert into CASSIE.SUBJECT (S_NO,BT_NO,S_CONTENT) values (24,7,'정보 수정');
Insert into CASSIE.SUBJECT (S_NO,BT_NO,S_CONTENT) values (25,7,'무인도 게시판');
Insert into CASSIE.SUBJECT (S_NO,BT_NO,S_CONTENT) values (26,7,'기타');
Insert into CASSIE.SUBJECT (S_NO,BT_NO,S_CONTENT) values (27,8,'회원 관련 문의');
Insert into CASSIE.SUBJECT (S_NO,BT_NO,S_CONTENT) values (28,8,'결제 관련 문의');
Insert into CASSIE.SUBJECT (S_NO,BT_NO,S_CONTENT) values (29,8,'정보수정 요청');
Insert into CASSIE.SUBJECT (S_NO,BT_NO,S_CONTENT) values (30,8,'무인도 관련 문의');
Insert into CASSIE.SUBJECT (S_NO,BT_NO,S_CONTENT) values (31,8,'기타 문의');
Insert into CASSIE.SUBJECT (S_NO,BT_NO,S_CONTENT) values (32,9,'판매중');
Insert into CASSIE.SUBJECT (S_NO,BT_NO,S_CONTENT) values (33,9,'구매중');
Insert into CASSIE.SUBJECT (S_NO,BT_NO,S_CONTENT) values (34,9,'거래완료');
